version: "3.6"

services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.92.0
    command: --config=/etc/otelcol/config.yaml
    volumes:
      - ./collector.yaml:/etc/otelcol/config.yaml  # Ensure this path matches the config file name
    environment:
      - CONFLUENT_API_KEY=<api_key>
      - CONFLUENT_API_SECRET=<api_secret>
      - NEW_RELIC_LICENSE_KEY=<license_key>
      - CLUSTER_ID=<cluster_id>
