apiVersion: v1
kind: Secret
metadata:
  name: nr-confluent-secret
  namespace: nr-confluent
stringData:
  # New Relic API key to authenticate the export requests.
  # docs: https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#license-key
  NEW_RELIC_API_KEY: <api_key>
  # Set your authentication keys for the Confluent Cloud metrics API.
  # docs: https://docs.confluent.io/cloud/current/monitoring/metrics-api.html
  CONFLUENT_API_KEY: <api_key_confluent>
  CONFLUENT_API_SECRET: <api_secret_confluent>
