apiVersion: v1
kind: Secret
metadata:
  name: nr-confluent-secret
  namespace: nr-confluent
stringData:
  # New Relic API key to authenticate the export requests.
  # docs: https://docs.newrelic.com/docs/apis/intro-apis/new-relic-api-keys/#license-key
  NEW_RELIC_API_KEY: 7f6975a49e87827ad4d347e6786efd83FFFFNRAL
  # Set your authentication keys for the Confluent Cloud metrics API.
  # docs: https://docs.confluent.io/cloud/current/monitoring/metrics-api.html
  CONFLUENT_API_KEY: AZCHIZY7RUBKFAHY
  CONFLUENT_API_SECRET: W8WlvIGd3Uj3eyBfUl1VCadkIxuA/SG+jQ6XkhnQPrNSxiIAq1t4N/VQSwZjkhYm
